""" Initialisation of aws package and creation of several variable """
STUDENT_ID = "s3989748"
END_MAIL = "@student.rmit.edu.au"
FIRST_NAME = "Alexis"
LAST_NAME = "IMBERT"

JSON_FILE_PATH = "./s3989748/aws/a1.json"

DB_MUSIC = "music"
DB_LOGIN = "login"
BUCKET_MUSIC_NAME = "s3989748-music-s3"
REGION = "us-east-1"

KEY_ID = "ASIAQTDQASWDBWUUGCFO"
ACCESS_KEY = "+TusUTd+SbbXuGL1gLNSB9mhzIThxqpw795b1pWE"
TOKEN = "FwoGZXIvYXdzEDAaDBUq0uj9eKrWjkdhHSLNASDFgRxDUkFw9BZ8fYnYAnswnINYombQPxO5701PYuUrMrrTLQhdprLE6TEUh9JRIHqLDEnPn5cjKHPsRRm9OIr4hwe1r273fC0bxt4M96GeXdRyWRphKExdFIsMnsRarDqleIP6VtsXYgS6TXDxSGFdMeFiM8Oax19Ln3WPfKcBibHmbLCTINjRYnbJtD/IPqdsowD7E6aJ2JoL5uTVp4k7mU8DSCNWViJqDXCoDit/1OKyRC+MAk6cJ1SqAIsLQ+a2YoAUkBZDxAq0XvAorsyyoQYyLZ+lksRP6gM7kcWK6rnA3rjDudwFuPXgJhYnjRF1UJX9T+BzU2LqorduIGXAEg=="
